### ISSUE TITLE
Problem with file extension in database

### ISSUE THREAD

**Issue by Corentin7301** [kevcomparadise/directus-vue3-cloudinary-upload#6]
In database, the image name has double extensions like: `-------/blobs.png.png`.
I don't know why I've this bug.
In Cloudinary, the file has a good simple extension like `-------/blobs.png`.

**Comment by kschnekenburger** [comment]
@Corentin7301 I just noticed that Directus has been updated and they provide a Cloudinary driver in the box !
https://docs.directus.io/self-hosted/config-options.html#cloudinary-cloudinary

I'm closing this issue and archiving the repository.
